// Generated by https://quicktype.io

export interface IMetrics {
    cpuUsage:    string;
    memoryUsage: MemoryUsage;
}

export interface MemoryUsage {
    memory: Memory;
    swap:   Memory;
}

export interface Memory {
    total: string;
    used:  string;
}
